routes/web.php
<?php

use App\Professional;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/





Route::get('/', 'FrontpageController@index');
//Route::get('/setcookie', 'FrontpageController@setCookie')->middleware('auth');




//Route::view('/', 'pages.home');

Route::view('/about', 'pages.about', ['page_title' => config('app.name').' | About us']);
Route::view('/membership', 'pages.membership', ['page_title' => config('app.name').' | Membership']);
Route::view('/privacy', 'pages.privacy');
Route::view('/terms', 'pages.terms');
Route::view('/find', 'pages.findus');
Route::view('/opening', 'pages.opening');

//Route::view('/classes', 'pages.classes', ['page_title' => config('app.name').' | Classes']);
Route::get('/classes', 'ClassesController@index');
Route::view('/gallery', 'pages.gallery', ['page_title' => config('app.name').' | Gallery']);


Route::view('/greatineight', 'pages.greatineight',['page_title' => config('app.name').' | Great in Eight']);
Route::get('/trainers','ProfessionalsController@list_trainers');
Route::get('/therapists','ProfessionalsController@list_therapists');

Route::get('/profile/{slug}/{simple?}','ProfessionalsController@show');


Route::get('/contact', 'ContactController@index');
Route::post('/contact/send', 'ContactController@send')->middleware(protspam::class);
Route::post('/professional/send', 'ProfessionalsController@send');
//Experimental


//Admin section Routes

Auth::routes(['register' => false]);

Route::middleware('auth')->group(function () {
    Route::get('/home', 'Admin\HomeController@index')->name('home');
    Route::get('/admin/therapists', 'Admin\ProfessionalsController@list_therapists');
    Route::get('/admin/trainers', 'Admin\ProfessionalsController@list_trainers');

    Route::get('/admin/professional/create_therapist', 'Admin\ProfessionalsController@create_therapist');
    Route::get('/admin/professional/create_trainer', 'Admin\ProfessionalsController@create_trainer');
    Route::get('/admin/professional/{professional}', 'Admin\ProfessionalsController@show');
    Route::get('/admin/professional/{professional}/edit', 'Admin\ProfessionalsController@edit');


    Route::post('/admin/professional/update/{professional}', 'Admin\ProfessionalsController@update');
    Route::post('/admin/professional/store', 'Admin\ProfessionalsController@store');

    Route::get('/admin/page', 'Admin\PagesController@show');
    Route::get('/admin/page/{page}/edit', 'Admin\PagesController@edit');
    Route::post('/admin/page/update/{page}', 'Admin\PagesController@update');

    Route::get('/admin/classes', 'Admin\HomeController@classes');

    Route::post('/upload', 'Admin\ProfessionalsController@upload');

    Route::get('/setcookie', 'FrontpageController@setCookie');

});

app/ClassTimetable.php
<?php

namespace App;

use App\Professional;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\Types\Collection;

class ClassTimetable extends Model
{
    protected $table='class_timetable';

    protected $guarded=[];

    public function professional(){
        return $this->belongsTo('App\Professional', 'partner_id');
    }
    public function getEndTimeAttribute()
    {
        $time = strtotime($this->start_time);

     return date("H:i", strtotime($this->duration.'minutes', $time));



    }


}

resources/views/pages/about.blade.php
@extends('layouts.default')
@section('content')

  <!-- About -->
<!-- Header -->

  
  <section class="page-section" id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">About us</h2>
          <h3 class="section-subheading text-muted"></h3>
        </div>
      </div>
      <div class="row">
<div class="col-lg-12">
<p>
        The West 4 Gym management team Sam Stone and Paul Lovelace took over West 4 Gym on 1st January 2016.  Sam had been the Manager for 15 years prior to taking over. Paul was originally a member and then joined as a Personal Trainer. Both are West London born and bred, with Sam originally from Kew and Paul from Chiswick. 
      </p>
</div>  

<div class="col=lg-12 mx-auto">
           <img src="https://res.cloudinary.com/west4gym-co-uk/image/upload/c_scale,h_250/v1584527921/paul_and_sam_iwmkfu.jpg">

</div>
        <div class="col-lg-12 pb-5">
       
<p>Sam and Paul have both seen the area change a lot during the last few years, but have an ongoing commitment to creating a unique space for their members - the 300 Spartans.  “The 300 Spartans captures the spirit of the club - with a personal service that enables each individual to meet their needs with a collective friendly environment”.  
        </p><p>Sam and Paul have added a Treatment Room, put in new lighting, and installed new cardio equipment.  The Treatment Room has been a success, hosting a range of Independent Therapists providing Osteopathy, rehabilitation and Sports Massage. 

        </p><p>For those occasions where two heads are greater than one we have an excellent group of Personal Trainers.
        </p><p>We run a number of High Intensity Interval Training classes - in Paul's words “If you want to get fit fast - this is the way to go”.
        </p></div>
      </div> 
    </div>
  </section>
  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  @stop

resources/views/pages/classes.blade.php
@extends('layouts.default')
@section('content')

<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Class Timetable</h2>

        </div>
    </div>
</header>



  <!-- Contact -->

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-auto">

    <table class="table table-bordered" >

  <thead>
    <tr>
      <th scope="col">Day</th>
        <th scope="col">Description</th>
      <th scope="col">Time</th>
      <th scope="col">Charge</th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <th scope="row" >Monday</th>
      <td>Circuit Training</td>
      <td>19:00 - 19.45</td>
      <td>Free</td>
    </tr>

    <tr>
        <th scope="row">Wednesday</th>
        <td>Boxing with <a href="/profile/25">Lloyd</a></td>
        <td>19.15 - 20.30</td>
        <td>&pound;15</td>
    </tr>
    <tr>
        <th scope="row" >Thursday</th>
        <td>Circuit Training</td>
        <td>19:00 - 19.45</td>
        <td>Free</td>
    </tr>

    <tr>
      <th scope="row">Saturday</th>
      <td>HIIT</td>
      <td>12.00 - 12.45</td>
      <td>Free</td>
    </tr>
    <tr>
        <th scope="row">Saturday</th>
        <td>Yoga with <a href="/profile/24">Anna</a></td>
        <td>7.45 - 8.45 AM</td>
        <td><a href="/profile/24">see profile</a></td>
    </tr>

  </tbody>
</table>


</div>
        </div>









    </div> <!--container-->

  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  @stop

resources/views/pages/classestable.blade.php
@extends('layouts.default')
@section('content')

<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Class Timetable</h2>

        </div>
    </div>
</header>



  <!-- Contact -->

    <div class="container">

        <div class="row justify-content-center">
            <div class="col-auto">

    <table class="table table-bordered table-primary table-responsive-sm" >

  <thead>
    <tr>
      <th scope="col">Day</th>
        <th scope="col">Description</th>
      <th scope="col">Time</th>
      <th scope="col">Charge</th>
    </tr>
  </thead>
  <tbody>
@foreach($classes as $c)
    <tr>
      <th scope="row" > {{jddayofweek($c->day-1, 1)}}</th>
 
        <td>
          @if($c->professional==null)
          {{$c->description}} 
      @else
          {{$c->description}}  with <a href="/profile/{{$c->professional->slug}}">{{$c->professional->fname}}</a>
      @endif
        </td>
      <td>{{$c->start_time}} - {{$c->end_time}}</td>
        <td>{{$c->charge? $c->charge : 'Free'}}</td>
    </tr>
@endforeach


  </tbody>
</table>


</div>
        </div>









    </div> <!--container-->

  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  @stop

resources/views/pages/contact.blade.php
@extends('layouts.default')
@section('content')
<!-- Header -->
<header class="membership">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Contact us</h2>
            <h3 class="section-subheading text-muted"></h3>
        </div>
    </div>
        @push('liveStyles')
            @livewireStyles
    @endpush
</header>



  <!-- Contact -->

    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <p class="contact">Please feel free to swing by the gym to get a feel of the place. We are always interested in understanding more about your fitness goals whether that be maintaining a healthy body or training for a big event. Check out our <a href="/find" >opening times</a>.</p>
    </div>

    </div>


@if ($message = Session::get('success'))<div class="row">
<div class="col-lg-12">
   <div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
           <strong>{{ $message }}</strong>
   </div>
</div>
</div>
@endif
      <div class="row">
        <div class="col-lg-12">


          <form action="{{ url('/contact/send')}}" method="post" id="contact">
          @csrf
          <x-honeypot />
 
                <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <input class="form-control"
                    name="name"
                    id="name"
                    type="text"
                    value="{{old('name')}}"
                    placeholder="Your Name *"
                    required="required"
                    data-validation-required-message="Please enter your name.">
                  <p class="help-block text-danger">{{$errors->first('name')}}</p>
                </div>
                <div class="form-group">
                    <input class="form-control"
                    name="email"
                    id="email"
                    value= "{{old('email')}}"
                    type="email"
                    placeholder="Your Email *"
                    data-validation-required-message="Please enter your email address.">
                    <p class="help-block text-danger" >{{$errors->first('email')}}</p>
                </div>
                 <div class="form-group">
                    <input class="form-control"
                    name="tel"
                    id="phone"
                    value="{{old('tel')}}"
                    type="tel"
                    placeholder="Your Phone *"
                    data-validation-required-message="Please enter a phone number.">
                  <p class="help-block text-danger">{{$errors->first('tel')}}</p>
                </div>


              </div>
                    <div class="col-md-6">
                <div class="form-group">
                  <textarea class="form-control"
                  name="message"
                  id="message"
                  placeholder="Your Message *
                  "data-validation-required-message="Please enter your email address." >{{old('message')}}</textarea>
                  <p class="help-block text-danger">{{$errors->first('message')}}</p>
                </div>
              </div>
              <div class="clearfix"></div>
              <div class="col-lg-12 text-center py-5">
                <div id="success"></div>
                <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>

              </div>
            </div>
          </form>

        </div>
      </div>



    </div> <!--container-->

  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>


  <!-- Contact form JavaScript -->
  <script src="{{asset('/assets/js/jqBootstrapValidation.js')}}"></script>
  @stop
@push('liveScripts')
    @livewireScripts
@endpush

resources/views/pages/contact_bak.blade.php
@extends('layouts.default')
@section('content')
<!-- Header -->
<header class="membership">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Contact</h2>
            <h3 class="section-subheading text-muted"></h3>
        </div>
    </div>
</header>


   
  <!-- Contact -->
 
    <div class="container">
    <div class="row">
    <div class="col-lg-12">
    <p>Please feel free to swing by the gym to get a feel of the place. We are always interested in understanding more about your fitness goals whether that be maintaining a healthy body or training for a big event. Check out our <a href="/find">opening times</a>.</p>
    </div>

    </div>


@if ($message = Session::get('success'))<div class=row>
<div class="col-lg-12">
   <div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
           <strong>{{ $message }}</strong>
   </div>
</div>
</div>
@endif
      <div class="row">
        <div class="col-lg-12">
          <form action="{{ url('/contact/send')}}" method="post">
          {{csrf_field()}}
          @honeypot
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <input class="form-control" name="name" id="name" type="text" placeholder="Your Name *" required="required" data-validation-required-message="Please enter your name.">
                  <p class="help-block text-danger"></p>
                </div>
                <div class="form-group">
                  <input class="form-control" name="email" id="email" type="email" placeholder="Your Email *" required="required" data-validation-required-message="Please enter your email address.">
                  <p class="help-block text-danger"></p>
                </div>
                <div class="form-group">
                  <input class="form-control" name="tel" id="phone" type="tel" placeholder="Your Phone *" required="required" data-validation-required-message="Please enter your phone number.">
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <textarea class="form-control" name="content" id="message" placeholder="Your Message *" required="required" data-validation-required-message="Please enter a message."></textarea>
                  <p class="help-block text-danger"></p>
                </div>
              </div>
              <div class="clearfix"></div>
              <div class="col-lg-12 text-center py-5">
                <div id="success"></div>
                <button id="sendMessageButton" class="btn btn-primary btn-xl text-uppercase" type="submit">Send Message</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    
   
   
    </div> <!--container-->
 
  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

  <!-- Contact form JavaScript -->
  <script src="{{asset('/assets/js/jqBootstrapValidation.js')}}"></script>
  @stop

resources/views/pages/findus.blade.php
@extends('layouts.default')
@section('content')
<!-- Header -->
@push('liveStyles')
    <style>
      html, body, #map { height: 100%; margin: 0; }
    </style>
@endpush
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Find us</h2>
          </div>
    </div>
 
</header>


   
  <!-- Contact -->
 
    <div class="container">
    <div class="row py-5">
    <div class="col-md-6">
    <div id="map"></div>
    <address class="pt-5">West4 Gym <br />Sutton Lane North<br />Chiswick W4 4LD </address>

    </div>
    <div class="col-md-6">
    <img class="float-right img-fluid max-width: 100%" src="{{asset('assets/img/edificio.jpg')}}"  alt="Responsive image" />
    </div>

    </div>




    

   
    </div> <!--container-->
 
  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

      <script>

// Initialize and add the map
function initMap() {
  // The location of Uluru
  var west4 = {lat: 51.489270, lng: -0.269980};
  // The map, centered at Uluru
  var map = new google.maps.Map(
      document.getElementById('map'), {zoom: 12, center: west4});
  // The marker, positioned at Uluru
  var marker = new google.maps.Marker({position: west4, map: map});
}
    </script>
    <!--Load the API from the specified URL
    * The async attribute allows the browser to render the page while the API loads
    * The key parameter will contain your own API key (which is not needed for this tutorial)
    * The callback parameter executes the initMap() function
    -->
  <script async defer
   src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDThlC8o0xBWjMTbIcas9fI8l_M_oPg-WQ&callback=initMap">
   </script>
 
  @stop

resources/views/pages/membership.blade.php
@extends('layouts.default')
@section('content')
<!-- Header -->
<header class="membership">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Membership</h2>
                <h3 class="section-subheading text-muted">Call or <a href="/contact" >email </a> to book a tour during opening hours.</h3>


        </div>
    </div>
</header>

    <div class="container">
        <div class="row mb-5">
            <div class="col-md-6 p-0 m-0">
                {{-- <img src="https://res.cloudinary.com/west4gym-co-uk/image/upload/v1597069910/annyhooker_pwd4y7.jpg" style="width:100%"> --}}
                <img src="https://res.cloudinary.com/west4gym-co-uk/image/upload/v1626863148/4F2BDDB0-F17D-45D8-BC31-B85E54EB5A6C.resized_nx3cqh.jpg" class="img-fluid max-width: 100%" >
            </div>
            <div class="col-md-6 p-0 m-0">

                <img  src="https://res.cloudinary.com/west4gym-co-uk/image/upload/v1626863710/07EB3D0E-9630-4FB9-AD6B-422D401AB843.resized_giguly.jpg" class="img-fluid max-width: 100%" >
            </div>
        </div>
        <div class="row text-center ">

            <div class="col-md-4">
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x text-secondary"></i>
                    <strong class="fa-stack-1x fa-inverse">
                    1
                    </strong>
                </span>
                <h4 class="pt-3">Pay as you go</h4>
                <p class="text-muted">£80/month <br/>£15 Guest Day Pass</p>
            </div>
            <div class="col-md-4">
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x text-secondary"></i>
                    <strong class="fa-stack-1x fa-inverse">
                    2
                    </strong>
                </span>
                <h4 class="pt-3">Individual</h4>
                <p class="text-muted">£70/month or *£750/year <br/>Payment by Direct Debit<br/> * Subject to £25 Admin Fee.</p>
            </div>
            <div class="col-md-4">
            <span class="fa-stack fa-4x">
                <i class="fas fa-circle fa-stack-2x text-secondary"></i>
                    <strong class="fa-stack-1x fa-inverse">
                    3
                    </strong>
                </span>
                <h4 class="pt-3">Junior</h4>
                <p class="text-muted">£50/month<br/>Age 16 - 18</p>
            </div>
        </div>




        <div class="row text-center">
	        <div class="col-md-12 pt-5  pb-5">
                <h3>Refreshingly flexible membership terms</h3>
                <ul class="list-unstyled">

            <li>No long term contracts. </li>
            <li>No complicated cancellation process, just drop us an email to cancel with just one payments notice.</li>
            </ul>
                <h3 class="pt-3">New Individual Member Benefits</h3></ul>
                <ul class="list-unstyled">
                <li>Two complimentary guest passes worth £20</li>

            <li>Consultation with a personal trainer</li>
            <li>Personalized training programme</li>
             <li>Applies solely to Individual Memberships</li>
        </ul>
            </div><!--col-->
	    </div><!--row-->


    </div> <!--container-->

  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  @stop

resources/views/pages/opening.blade.php
@extends('layouts.default')
@section('content')
<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Opening Times</h2>

        </div>
    </div>
</header>



  <!-- Contact -->

    <div class="container">
 <div class="row py-5">
     <div class="col-md-6 offset-md-3">

      <table class="table table-primary table-bordered">
    <thead>
      <tr>
        <th>Day</th>
        <th>Opens </th>
        <th>Closes</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Monday</td>
        <td>7.00</td>
        <td>21.00</td>
      </tr>
      <tr>
        <td>Tuesday</td>
        <td>7.00</td>
        <td>21.00</td>
      </tr>      <tr>
        <td>Wednesday</td>
        <td>7.00</td>
        <td>21.00</td>
      </tr>      <tr>
        <td>Thursday</td>
        <td>7.00</td>
        <td>21.00</td>
      </tr>            <tr>
        <td>Friday</td>
        <td>7.00</td>
        <td>20.00</td>
      </tr>
      <tr>
        <td>Saturday</td>
        <td>9.00</td>
        <td>17.00</td>
</tr>
        <tr>
        <td>Sunday</td>
        <td>9.00</td>
        <td>17.00</td>
      </tr>
    </tbody>
  </table>
</div>
</div>

    </div> <!--container-->

  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDThlC8o0xBWjMTbIcas9fI8l_M_oPg-WQ"></script>
  @stop

resources/views/pages/partner.blade.php
@extends('layouts.default')
@section('content')
<!-- Header -->
<header>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">{{ $profile->fname }} {{$profile->lname}}</h2>
            </div>
        </div>
    </div>
</header>

 
<div class="container">
    <div class="row py-3">
        <div class="col-md-4 pb-3">
            <img class="card-img-top" src="{{ $profile->image_cloud }}" alt="Card image" style="width:100%">
        </div>
        <div class="col-md-8 profile">
            {!! $profile->long_desc !!}
        </div>
                
    </div>
                                            
</div>

    	   
	   

 
  @stop
  @section('myjs')
    <!-- Bootstrap core JavaScript -->
  <script src="{{asset('/assets/vendor/jquery/jquery.min.js')}}"></script>
  <script src="{{asset('/assets/vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
  @stop

resources/views/pages/privacy.blade.php
@extends('layouts.default')
@section('content')

  <!-- About -->
<!-- Header -->

  
<header>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Privacy</h2>
        </div>
     </div>
</header>
<div class="container">
     <div class="row">
        <div class="col-lg-12 pb-5">
        <p>We collect certain information or data about you when you use phplaravel-349008-1093391.cloudwaysapps.com.</p>

<p>This includes:
<ul>
<li>questions, queries or feedback you leave, including your email address if you send a message or email</li>
<li>your IP address, and details of which version of web browser you used</li>
<li>information on how you use the site, using cookies and page tagging techniques to help us improve the website</li>
</ul>
</p>
<p>This helps us to:</p>
<ul>
<li>improve the site by monitoring how you use it</li>
<li>respond to any feedback you send us, if you’ve asked us to</li>
<li>We can’t personally identify you using your data.</li>
</ul>
<h4>WHERE YOUR DATA IS STORED</h4>
<p>We store your data on our secure servers in the UK. It may also be stored outside of Europe, where it could be viewed by our staff or suppliers. By submitting your personal data, you agree to this.

<h4>KEEPING YOUR DATA SECURE</h4>
<p>Transmitting information over the internet is generally not completely secure, and we can’t guarantee the security of your data. Any data you transmit is at your own risk. We have procedures and security features in place to try and keep your data secure once we receive it. We won’t share your information with any other organisations for marketing, market research or commercial purposes, and we don’t pass on your details to other websites.

You can find out what information we hold about you, and ask us not to use any of the information we collect. Links to other websites phplaravel-349008-1093391.cloudwaysapps.com contains links to and from other websites. This privacy policy only applies to this website, and doesn’t cover other services and transactions that we link to. Following a link to another website If you go to another website from this one, read the privacy policy on that website to find out what it does with your information. Following a link to phplaravel-349008-1093391.cloudwaysapps.com from another website If you come to phplaravel-349008-1093391.cloudwaysapps.com from another website, we may receive personal information about you from the other website.</p>
</div>
      </div>
    </div>  
  @stop